server:
  port: 8020
logging:
  level:
    com.aisino: debug
spring:
  application:
    name: user-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springbootdemo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8010/eureka,http://127.0.0.1:8011/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
mybatis:
  configuration:
    #    驼峰
    map-underscore-to-camel-case: true
  #    扫描配置
  #  dao-locations: dao/*.xml
  #  别名扫描包
  type-aliases-package: com.aisino.pojo
